// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyR4sEsRql_ei2SMKjHebBrUbSKaFt9s',
    appId: '1:140744396222:web:520ec26b9ca774326abdef',
    messagingSenderId: '140744396222',
    projectId: 'stroke-ai-app',
    authDomain: 'stroke-ai-app.firebaseapp.com',
    storageBucket: 'stroke-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4LTx4-4k7P7fngkpIe4ma2O9Ytd5yPks',
    appId: '1:140744396222:android:755b4b12505285db6abdef',
    messagingSenderId: '140744396222',
    projectId: 'stroke-ai-app',
    storageBucket: 'stroke-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1YGRlfCfMViEib0H38mYU30fnTOZtMU',
    appId: '1:140744396222:ios:3a0dc1f0ab81e36d6abdef',
    messagingSenderId: '140744396222',
    projectId: 'stroke-ai-app',
    storageBucket: 'stroke-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.assistantstroke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV1YGRlfCfMViEib0H38mYU30fnTOZtMU',
    appId: '1:140744396222:ios:3a0dc1f0ab81e36d6abdef',
    messagingSenderId: '140744396222',
    projectId: 'stroke-ai-app',
    storageBucket: 'stroke-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.assistantstroke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHyR4sEsRql_ei2SMKjHebBrUbSKaFt9s',
    appId: '1:140744396222:web:474bae6753880b246abdef',
    messagingSenderId: '140744396222',
    projectId: 'stroke-ai-app',
    authDomain: 'stroke-ai-app.firebaseapp.com',
    storageBucket: 'stroke-ai-app.firebasestorage.app',
  );
}
